// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9zPxxtdngHegNbkVh_63Ww3z-D9CSy5M',
    appId: '1:235916611550:web:d8be5164179068a01e174f',
    messagingSenderId: '235916611550',
    projectId: 'time-tracker-flutter-app-c4a21',
    authDomain: 'time-tracker-flutter-app-c4a21.firebaseapp.com',
    storageBucket: 'time-tracker-flutter-app-c4a21.appspot.com',
    measurementId: 'G-Y0GG5KJ6YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsG-CK4zdZuRECLMQgsGSXHrPD33oDgc',
    appId: '1:235916611550:android:7ed701fb31864dde1e174f',
    messagingSenderId: '235916611550',
    projectId: 'time-tracker-flutter-app-c4a21',
    storageBucket: 'time-tracker-flutter-app-c4a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtAjCrOwxCcn4CAuOd65jl7s7O3lF6X0',
    appId: '1:235916611550:ios:7afa4d5f0172cb6b1e174f',
    messagingSenderId: '235916611550',
    projectId: 'time-tracker-flutter-app-c4a21',
    storageBucket: 'time-tracker-flutter-app-c4a21.appspot.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtAjCrOwxCcn4CAuOd65jl7s7O3lF6X0',
    appId: '1:235916611550:ios:7afa4d5f0172cb6b1e174f',
    messagingSenderId: '235916611550',
    projectId: 'time-tracker-flutter-app-c4a21',
    storageBucket: 'time-tracker-flutter-app-c4a21.appspot.com',
    iosBundleId: 'com.example.timeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9zPxxtdngHegNbkVh_63Ww3z-D9CSy5M',
    appId: '1:235916611550:web:accd49c7e9c0991d1e174f',
    messagingSenderId: '235916611550',
    projectId: 'time-tracker-flutter-app-c4a21',
    authDomain: 'time-tracker-flutter-app-c4a21.firebaseapp.com',
    storageBucket: 'time-tracker-flutter-app-c4a21.appspot.com',
    measurementId: 'G-M5D5F3QEQ3',
  );
}
